vcenter:
  host: 10.11.4.73                           # vCenter Server IP/FQDN
  username: Administrator@vsphere.local       # vCenter username
  password_env: VCENTER_PASSWORD              # Environment variable name
  validate_certs: false                       # SSL certificate validation

vms:
  - name: websrv-01                          # VM name (must be unique)
    template: Ubuntu-20                       # Source template name
    datacenter: Datacenter                    # Target datacenter
    cluster: cluster1                         # Target cluster
    datastore: datastore1                     # Target datastore
    hardware:                                 # Hardware specifications
      cpu: 2                                  # Number of vCPUs
      memory_mb: 4096                         # Memory in MB
      disk_gb: 40                             # Disk size in GB
    network:                                  # Network configuration
      name: VLAN_100                          # Port group name
      ip: 10.11.4.100                         # Static IP address
      netmask: 255.255.255.0                  # Subnet mask
      gateway: 10.11.4.1                      # Default gateway
      dns:                                    # DNS servers
        - 8.8.8.8
        - 8.8.4.4
